Document: urh
Title: Debian urh Manual
Author: <insert document author here>
Abstract: This manual describes what urh is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/urh/urh.sgml.gz

Format: postscript
Files: /usr/share/doc/urh/urh.ps.gz

Format: text
Files: /usr/share/doc/urh/urh.text.gz

Format: HTML
Index: /usr/share/doc/urh/html/index.html
Files: /usr/share/doc/urh/html/*.html
